# Generated by Django 4.1.2 on 2022-11-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_o_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='game',
            name='player_x_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
