# Generated by Django 4.1.2 on 2022-11-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0004_alter_game_player_o_alter_game_player_o_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.CharField(default='_________', max_length=9),
        ),
    ]
